name: Tests
on: [push, pull_request]

env:
    PHP_EXTENSIONS: mbstring, fileinfo

jobs:
    phpunit:
        name: PHP ${{ matrix.php }} on ${{ matrix.os }} (${{ matrix.dependency-version }})
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                php: [8.1, 8.2]
                dependency-version: [highest, lowest]
        steps:
            - uses: actions/checkout@v4.1.1

            - name: Configure PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: $PHP_EXTENSIONS
                  coverage: none

            - name: Restore Composer dependencies
              id: cache-php
              uses: actions/cache@v3
              with:
                  path: vendor
                  key: ${{ matrix.os }}-php-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-php-

            - name: Install dependencies
              if: steps.cache-php.outputs.cache-hit != 'true'
              uses: ramsey/composer-install@v2
              with:
                  dependency-versions: ${{ matrix.dependency-version }}
                  composer-options: "--prefer-dist"

            - name: Run PHPUnit tests
              run: vendor/bin/phpunit

    phpstan:
        name: Run PHPStan analysis
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4.1.1

            - name: Configure PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: latest
                  extensions: $PHP_EXTENSIONS
                  coverage: none

            - name: Restore Composer dependencies
              id: cache-php
              uses: actions/cache@v3
              with:
                  path: vendor
                  key: ${{ matrix.os }}-php-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-php-

            - name: Install dependencies
              if: steps.cache-php.outputs.cache-hit != 'true'
              uses: ramsey/composer-install@v2
              with:
                  dependency-versions: highest
                  composer-options: "--prefer-dist"

            - name: Run PHPStan analysis
              run: composer analyse
